project: 
  type: website

website: 
  page-navigation: true
  title: "Aishwarya Othena" 
  site-url: "https://aishwaryaothena.github.io/newwebsite/" 
  repo-url: "https://github.com/AishwaryaOthena/newwebsite"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#D9E3E4"
    logo: ""
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://aishwaryaothena.github.io/newwebsite
        text: "Website"
      - icon: github
        href: https://github.com/AishwaryaOthena/
        text: "Github"
      - icon: linkedin
        href: https://www.linkedin.com/in/aishwaryaothena
        text: "LinkedIn"
      - icon: instagram
        href: https://www.instagram.com/the_blind_bookworm
        text: "Instagram"


    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: content/cv.qmd
        text: My CV
      - href: content/publications.qmd
        text: My Publications
      - href: content/art.qmd
        text: My Art Portfolio
      - href: content/writing.qmd
        text: My Creative Writing

format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
